#ifndef LABRCTL_OPS_H
#define LABRCTL_OPS_H

#define LABRCTL_OP_USERSPACE 128

enum labrctl_op {
    LABRCTL_OP_NOP = 0,
    LABRCTL_OP_ACK = 1,
    LABRCTL_OP_RESEQ = 2,
    LABRCTL_OP_STORE = 3,
    LABRCTL_OP_FETCH = 4,
    LABRCTL_OP_SPAWN = 5,
    LABRCTL_OP_KILL = 6,
    LABRCTL_OP_GPUSIG0 = 128,
    LABRCTL_OP_GPUSIG1 = 129,
    LABRCTL_OP_GPUSIG2 = 130,
    LABRCTL_OP_GPUSIG3 = 131,
};

#endif // LABRCTL_OPS_H
